### ISSUE TITLE
Build nuget packages from this repository.

### ISSUE THREAD

**Issue by ngbrown** [rabbitmq/rabbitmq-dotnet-client#32]
For years, @joefitzgerald has been taking the official dll's and packaging them into nuget packages from a separate repository ([link](https://github.com/joefitzgerald/rabbitmq-dotnet-client-package)).  The .nuspec and build scripts should be moved to this repository so that future merges to support additional platforms (Windows Store and portable apps) can appropriately adjust the nuget generation.

**Comment by michaelklishin** [comment]
Agreed.

**Comment by joefitzgerald** [comment]
:+1:

**Comment by ngbrown** [comment]
Is there an updated document that outlines the entire process of using the various build scripts with what tools need to be installed?  The NuGet execution needs to be somewhere in those build scripts.

For example, the public-umbrella [build instructions](https://github.com/rabbitmq/rabbitmq-public-umbrella/tree/master/release-build) mentions <http://moshi.lshift.net/RabbitMQDotnetClientReleaseProcess> but that is a dead link.

Is all the mono build switching still relevant? It seems that building on Windows and then testing on both Windows and Mono would be acceptable.

**Comment by michaelklishin** [comment]
@ngbrown see http://www.rabbitmq.com/build-dotnet-client.html. Building on Windows for NuGet makes sense.

**Comment by michaelklishin** [comment]
@ngbrown I've updated the pages. VS 2013, .NET 4 and `cp Local.props.example Local.props` is all you need these days. Then simply run `msbuild.exe`.

**Comment by michaelklishin** [comment]
I'd really like to see NuGet scripts to be in this repo. That's the easiest way to automated the rest for us and do manual releases as needed (e.g. to publish preview releases).

**Comment by joefitzgerald** [comment]
Perhaps a first easy step is to set up a CI build on AppVeyor (https://appveyor.com) against the public repo for the .NET client. From there, we start by publishing snapshot releases. Once everyone's comfortable with it, we could publish the actual releases once you're comfortable with the process.

**Comment by joefitzgerald** [comment]
@michaelklishin Can you give me commit rights to this repo so I can enable the builds on AppVeyor? Not a commitment to use it, but I'll push a branch and create a PR against it to review how this would look.

**Comment by michaelklishin** [comment]
@joefitzgerald you should have an invitation by now.

**Comment by ngbrown** [comment]
I did get a build running in appveyor <https://ci.appveyor.com/project/ngbrown/rabbitmq-dotnet-client/history>.

See my branch to get that working: <https://github.com/ngbrown/rabbitmq-dotnet-client/tree/feature-appveyor-ci>.  I to run the tests, I used `choco install rabbitmq`, used an environment variable for the `rabbitmqctl` location, and had to disable some tests that would fail on a single-core environment.

This is the configuration (exported `appveyor.yml`):

```yaml
version: 3.4.4.{build}
branches:
  only:
  - feature-appveyor-ci
environment:
  RABBITMQ_RABBITMQCTL_PATH: C:\Program Files (x86)\RabbitMQ Server\rabbitmq_server-3.4.1\sbin\rabbitmqctl.bat
install:
- ps: >-
    choco install rabbitmq -Version 3.4.1.0

    Set-Item -Path Env:\ERLANG_HOME -Value ([Environment]::GetEnvironmentVariables("Machine")["ERLANG_HOME"])
build_script:
- ps: >-
    dir env:\

    copy "Local.props.example" "Local.props"

    msbuild.exe
test:
  categories:
    except:
    - RequireSMP
```

**Comment by ngbrown** [comment]
The referenced pull request, #38, gets us partially there, but does not close this issue because it does not integrate an script into the repository to build the `.nupkg` files.

I have started working on a msbuild proj file, but it was easier to get it working using PowerShell scripts in AppVeyor.  See the end for a discussion on this.

The nuget files are being generated from my fork.  View project's latest build and history here: <https://ci.appveyor.com/project/ngbrown/rabbitmq-dotnet-client>

Use feed in nuget (with prerelease option): <https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-q24w9pde6mxu>

See feed entries in browser: [link](https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-q24w9pde6mxu/Search()?$skip=0&$top=30&searchTerm=%27%27&includePrerelease=true)

The current configuration includes scripts to takes the automatic version number, inject it into `Local.props` for the build and rearrange it to a SemVer format with branch name (and limit to the 20 char max) for NuGet.

This is the configuration (exported `appveyor.yml`):

```yaml
version: 3.4.5.{build}
configuration: Release
platform: Any CPU
environment:
  RABBITMQ_RABBITMQCTL_PATH: C:\Program Files (x86)\RabbitMQ Server\rabbitmq_server-3.4.1\sbin\rabbitmqctl.bat
install:
- ps: >-
    choco install rabbitmq -Version 3.4.1.0

    Set-Item -Path Env:\ERLANG_HOME -Value ([Environment]::GetEnvironmentVariables("Machine")["ERLANG_HOME"])
cache: C:\Users\appveyor\AppData\Local\Temp\chocolatey\
before_build:
- ps: >-
    copy "Local.props.example" "Local.props"


    $localpropsitem = Get-ChildItem ".\Local.props"

    $xml = New-Object -TypeName XML

    $xml.Load($localpropsitem)

    $xml.Project.PropertyGroup.PropAssemblyVersion = ${env:APPVEYOR_BUILD_VERSION}

    $xml.Save($localpropsitem)
build:
  verbosity: minimal
test:
  categories:
    except:
    - RequireSMP
on_success:
- ps: >-
    $semver = ${env:APPVEYOR_BUILD_VERSION} -ireplace '(\d+.\d+.\d+).(\d+)', "`$1-ci`$2-${env:APPVEYOR_REPO_BRANCH}"

    $semver = $semver.Substring(0, [System.Math]::Min(20, $semver.Length))

    nuget pack RabbitMQ.Client.nuspec -version $semver -symbols

    nuget pack RabbitMQ.ServiceModel.nuspec -version $semver -symbols


    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
```

While the above file could be embedded in the repository and then versioned that way, I think it unduly ties the repository to AppVeyor.  I would prefer to be able to run the entire build script on my computer, including generating the nuspec files

Does the desire to use mono preclude using PowerShell?  Personally, I have not ever ran the `dist.sh` scripts because I develop on Windows and am not clear on exactly what needs installed.  Should the build go in those scripts or is an msbuild `build.proj` file ok?  Using the `build.proj` would move the `.sln` into the `projects` folder and call into it from there so msbuild would pick up the single proj file in the project root.
