### ISSUE TITLE
Consider adding static analysis

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#444]
There are a few analyzers provided by Microsoft: https://github.com/dotnet/roslyn-analyzers

There's also one from Sonar (https://www.nuget.org/packages/SonarAnalyzer.CSharp/) and their platform (https://www.sonarqube.org/).

There's also .editorconfig (https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options). This would enforce style on the code base and would prevent contributors to inadvertently make useless changes to the code.

**Comment by michaelklishin** [comment]
All good ideas but a `.editorconfig` perhaps should be its own issue.

**Comment by paulomorgado** [comment]
Done! #448

**Comment by lukebakken** [comment]
#689 resolved the `.editorconfig` suggestion.

**Comment by lukebakken** [comment]
Moving to version `7.0.0`. We would appreciate help on implementing the use of a static analyzer.

**Comment by stebet** [comment]
Challenge accepted :)

**Comment by asbjornu** [comment]
[Codacy](https://www.codacy.com/) is free for open source and is quite capable. It also supports SonarQube's configuration format so it can be committed to source. We use it and are quite happy with it. Someone with administrative rights to this repository can set up analysis by logging in to Codacy and performing a few steps.

If there's anything I can do to help, please holler!

**Comment by asbjornu** [comment]
[Infersharp](https://github.com/microsoft/infersharp) may also be a low-hanging fruit worth implementing since it's available as a [GitHub Action](https://github.com/marketplace/actions/c-code-analyzer):

```yaml
- name: Run C# Code Analyzer      
  uses: microsoft/CSharpCodeAnalyzer@v0.1
  id: runcsharpcodeanalyzer
  with:
    binary-path: '<path to the binary directory containing .dlls and .pdbs>'
- name: C# Code Analyzer analysis results
  run: echo "${{ steps.runcsharpcodeanalyzer.outputs.results }}"
```
