### ISSUE TITLE
Replace current build infra with Github Actions

### ISSUE THREAD

**Issue by danielmarbach** [rabbitmq/rabbitmq-dotnet-client#934]
I think it would be great for transparancy and evolvability perspective to switch to [github actions](https://github.com/features/actions)

For example

https://github.com/marketplace/actions/setup-rabbitmq-with-username-and-password

**Comment by stebet** [comment]
Makes sense. How hard is it to integrate rabbitctl into those?

**Comment by stebet** [comment]
If that's not possible, it's also possible to set up a CI build on Azure DevOps using the free-tier against the MS-hosted build agents and execute the builds in a container, including tests if more control is needed.

**Comment by asbjornu** [comment]
It's possible to use a Docker container directly in GitHub Actions with `uses: docker://rabbitmq:3.8.9-management-alpine` (I'm just a bit unsure about the exact syntax). It's also possible to bundle a `Dockerfile` and do `docker build` and `docker run` directly. Azure DevOps should not be needed.

**Comment by asbjornu** [comment]
Just for the fun of it, I did a spike in asbjornu/rabbitmq-dotnet-client#1 that just replaces CI, but keeps the scripts and process. It works for Linux, not yet sure for Windows.

**Comment by stebet** [comment]
```
.github/workflows/dotnet-core.yml
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      rabbitmq:  
        image: rabbitmq:3.8.9-management
        ports:
         - 5672:5672
         - 15672:15672
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --framework 'netcoreapp3.1' --no-build
      env:
        RABBITMQ_RABBITMQCTL_PATH: DOCKER:${{job.services.rabbitmq.id}}
```

This works and might be a good initial step for CI builds (doesn't set SourceLink etc. but compiles and runs the tests targeting netcoreapp3.1).
